### ISSUE TITLE
wasm2wat: initializer expression cannot reference a mutable global

### ISSUE THREAD

**Issue by orestisfl** [fitzgen/wasm-smith#18]
Using wasm-smith built from the main branch can generate a module that wabt fails to validate (https://github.com/WebAssembly/wabt/blob/be5e8bf8ec698f9ad3a1b6fbb412680995fe39bf/src/shared-validator.cc#L204).

See attached zip file. `inp.bytes` is the input used and `test.wasm` is the produced module.

[error.zip](https://github.com/fitzgen/wasm-smith/files/5361156/error.zip)

With `wasm2wat --no-check` the output is:
```
(module
  (import "" "" (table (;0;) 504174 funcref))
  (import "$" "" (global (;0;) (mut f64)))
  (import "" "" (memory (;0;) 22217 39906))
  (global (;1;) i64 (i64.const -3518587451531543769))
  (global (;2;) (mut f64) (global.get 0)))
```

Is this a bug?

**Comment by fitzgen** [comment]
Looks like a bug, yeah. The second global is of type `f64` but is being initialized with an `i64` value.

**Comment by fitzgen** [comment]
Er wait I had an off by one. It is a bug, but the problem is that you can't use a mutable global as an initializer for another global.
